/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { MultiSigVault } from "./MultiSigVault";

export { MultiSigVault__factory } from "./factories/MultiSigVault__factory";
